### PR TITLE
Add again/menu option

### PR DESCRIPTION
**Pull request by elfotux**
Again it was added the option to choose the file name.
I would like to standardize the colors of the texts.
It is my suggestion:
Avoid the red color, because reading and viewing is not good on the screen.
I changed the red text to yellow.
Let's keep this pattern.
Summing up:
Post questions or alerts are yellow in color
And it is an observation, careful when climbing their code and files, for what had been removed, but is already corrected by me.

thank you

### CODE REVIEW

**Comment by elfotux** [comment]
I would also point out regarding the variables that were in the code.
For example: $ text and $ text2.
I would avoid the memory use in creating variables that already exist in the script.
In a piece of code I changed some variables only uilizando a single call.
Thus, subtly, the performace will be higher and the code of understanding will be easier for other developers github.

What do you think?

Thank you.

**Comment by UserXGnu** [comment]
There's some conflicts on your branch that you need fo fix before merging. About the variables like text and text2, I agree that their names should be more suggestive or something like that! However, about what you said, I think that you misunderstood what those variables means, they're not the same and they serve to different purposes. There's no reason to remove any of them.

**Comment by elfotux** [comment]
Ok, easy. 
The next face meeting, explaining about the changes in the variables.
And the rest of the code?
Only one thing, someone climbed without the merge thus erasing my last commit

**Comment by UserXGnu** [comment]
Alright, we can do it! About the last upload, there was an upload right into the 1.0-ruby branch. Some code was lost including yours! That's why I think that we need the manage the project files.

**Comment by elfotux** [comment]
Right, I'm waiting for everbody say ok for do that and close the pull request.

Thank's guys

**Pull request closed without merging**
