### PR TITLE
[cipher_utils]

### PR DESCRIPTION
**Pull request by UserXGnu**
Adding a new file and separating responsabilities in a proper way.

### CODE REVIEW

**Comment by n3k00n3** [comment]
Do you think that is better, put in the DOC or say in the code about random keys?

**Comment by UserXGnu** [comment]
Great, why didn't I think about this before? Got it!

**Comment by UserXGnu** [comment]
Done! Please, take a look at https://github.com/lampiaosec/virgulino/commit/3b6659ee7e74dc41b99e8f96d8ded5bf5817528d

**Comment by gjuniioor** [comment]
`doc/design.md` don't should be text format (to can used by `man`)?

**Comment by UserXGnu** [comment]
I know nothin about man pages, but you do! So please, fix it at your own will. ;)

**Comment by gjuniioor** [comment]
@elfotux : Man pages is your job

**Pull request closed without merging**
