### PR TITLE
Add/manpage

### PR DESCRIPTION
**Pull request by elfotux**
This is the file manpage for virgulino

### CODE REVIEW

**Comment by UserXGnu** [comment]
As I said before, please, create a milestone and set this pr and the related issue ok?

About the pr itself. I think that you need to read some man pages from common commands like: vim, ls, cp and so on..
You can't just copy the whole virgulino's wiki and put it into a file to say that it's a manpage. I know, I know, it's not easy...but there's no other way. 

Every switch that can be passed as argument must be present on the manpage with a whole explanation about what that parameter do and how to use it.

Anyway, I see that you're doing your best go on dude, you can do it!

Friday we can talk about the manpages so that you can see what i'm talking about ok?

kind regards

**Comment by gjuniioor** [comment]
This PR's is about #43, right? It's a good practice link them.

**Comment by UserXGnu** [comment]
Yeah, you're right. =-D

**Comment by UserXGnu** [comment]
Due to conflicts in your PR about virgulino.rb file, which wasn't the meaning of this PR by the way, I'll need to close this PR so that you can create a new one

**Pull request closed without merging**
