### PR TITLE
Simple text correction

### PR DESCRIPTION
**Pull request by lucascudo**

### CODE REVIEW

**Comment by UserXGnu** [comment]
There's already a PR fixing it! Closing!

**Comment by UserXGnu** [comment]
Thx dude, sorry for the mistake about this pr! Two versions of the same project can bring some trouble sometimes. Go ahead and merge it!

**Comment by gjuniioor** [comment]
Good attention!

**Comment by UserXGnu** [comment]
Sorry dude, to make the code maintenance easier we have decided to move the readme content to virgulino's wiki. Take a look at #35, sorry! Closing this pr and removing the branch, please rebase your project!

**Pull request closed without merging**
